export const districts = [
  {
    code: 102,
    name: 'Mongkol Borei',
    name_in_khmer: 'មង្គលបូរី',
    province_code: 1,
  },
  {
    code: 103,
    name: 'Phnum Srok',
    name_in_khmer: 'ភ្នំស្រុក',
    province_code: 1,
  },
  {
    code: 104,
    name: 'Preah Netr Preah',
    name_in_khmer: 'ព្រះនេត្រព្រះ',
    province_code: 1,
  },
  { code: 105, name: 'Ou Chrov', name_in_khmer: 'អូរជ្រៅ', province_code: 1 },
  {
    code: 106,
    name: 'Serei Saophoan',
    name_in_khmer: 'សិរីសោភ័ណ',
    province_code: 1,
  },
  { code: 107, name: 'Thma Puok', name_in_khmer: 'ថ្មពួក', province_code: 1 },
  { code: 108, name: 'Svay Chek', name_in_khmer: 'ស្វាយចេក', province_code: 1 },
  { code: 109, name: 'Malai', name_in_khmer: 'ម៉ាឡៃ', province_code: 1 },
  { code: 110, name: 'Paoy Paet', name_in_khmer: 'ប៉ោយប៉ែត', province_code: 1 },
  { code: 201, name: 'Banan', name_in_khmer: 'បាណន់', province_code: 2 },
  { code: 202, name: 'Thma Koul', name_in_khmer: 'ថ្មគោល', province_code: 2 },
  {
    code: 203,
    name: 'Battambang',
    name_in_khmer: 'បាត់ដំបង',
    province_code: 2,
  },
  { code: 204, name: 'Bavel', name_in_khmer: 'បវេល', province_code: 2 },
  { code: 205, name: 'Aek Phnum', name_in_khmer: 'ឯកភ្នំ', province_code: 2 },
  {
    code: 206,
    name: 'Moung Ruessei',
    name_in_khmer: 'មោងឫស្សី',
    province_code: 2,
  },
  {
    code: 207,
    name: 'Rotonak Mondol',
    name_in_khmer: 'រតនមណ្ឌល',
    province_code: 2,
  },
  { code: 208, name: 'Sangkae', name_in_khmer: 'សង្កែ', province_code: 2 },
  { code: 209, name: 'Samlout', name_in_khmer: 'សំឡូត', province_code: 2 },
  { code: 210, name: 'Sampov Lun', name_in_khmer: 'សំពៅលូន', province_code: 2 },
  {
    code: 211,
    name: 'Phnum Proek',
    name_in_khmer: 'ភ្នំព្រឹក',
    province_code: 2,
  },
  { code: 212, name: 'Kamrieng', name_in_khmer: 'កំរៀង', province_code: 2 },
  {
    code: 213,
    name: 'Koas Krala',
    name_in_khmer: 'គាស់ក្រឡ',
    province_code: 2,
  },
  {
    code: 214,
    name: 'Rukh Kiri',
    name_in_khmer: 'រុក្ខគិរី',
    district_code: 2,
  },
  { code: 301, name: 'Batheay', name_in_khmer: 'បាធាយ', district_code: 3 },
  {
    code: 302,
    name: 'Chamkar Leu',
    name_in_khmer: 'ចំការលើ',
    district_code: 3,
  },
  {
    code: 303,
    name: 'Cheung Prey',
    name_in_khmer: 'ជើងព្រៃ',
    district_code: 3,
  },
  {
    code: 305,
    name: 'Kampong Cham',
    name_in_khmer: 'កំពង់ចាម',
    district_code: 3,
  },
  {
    code: 306,
    name: 'Kampong Siem',
    name_in_khmer: 'កំពង់សៀម',
    district_code: 3,
  },
  { code: 307, name: 'Kang Meas', name_in_khmer: 'កងមាស', district_code: 3 },
  {
    code: 308,
    name: 'Kaoh Soutin',
    name_in_khmer: 'កោះសូទិន',
    district_code: 3,
  },
  { code: 313, name: 'Prey Chhor', name_in_khmer: 'ព្រៃឈរ', district_code: 3 },
  {
    code: 314,
    name: 'Srei Santhor',
    name_in_khmer: 'ស្រីសន្ធរ',
    district_code: 3,
  },
  {
    code: 315,
    name: 'Stueng Trang',
    name_in_khmer: 'ស្ទឹងត្រង់',
    district_code: 3,
  },
  { code: 401, name: 'Baribour', name_in_khmer: 'បរិបូណ៌', district_code: 4 },
  { code: 402, name: 'Chol Kiri', name_in_khmer: 'ជលគីរី', district_code: 4 },
  {
    code: 403,
    name: 'Kampong Chhnang',
    name_in_khmer: 'កំពង់ឆ្នាំង',
    district_code: 4,
  },
  {
    code: 404,
    name: 'Kampong Leaeng',
    name_in_khmer: 'កំពង់លែង',
    district_code: 4,
  },
  {
    code: 405,
    name: 'Kampong Tralach',
    name_in_khmer: 'កំពង់ត្រឡាច',
    district_code: 4,
  },
  {
    code: 406,
    name: "Rolea B'ier",
    name_in_khmer: 'រលាប្អៀរ',
    district_code: 4,
  },
  {
    code: 407,
    name: 'Sameakki Mean Chey',
    name_in_khmer: 'សាមគ្គីមានជ័យ',
    district_code: 4,
  },
  { code: 408, name: 'Tuek Phos', name_in_khmer: 'ទឹកផុស', district_code: 4 },
  { code: 501, name: 'Basedth', name_in_khmer: 'បរសេដ្ឋ', district_code: 5 },
  { code: 502, name: 'Chbar Mon', name_in_khmer: 'ច្បារមន', district_code: 5 },
  { code: 503, name: 'Kong Pisei', name_in_khmer: 'គងពិសី', district_code: 5 },
  { code: 504, name: 'Aoral', name_in_khmer: 'ឱរ៉ាល់', district_code: 5 },
  { code: 505, name: 'Odongk', name_in_khmer: 'ឧដុង្គ', district_code: 5 },
  {
    code: 506,
    name: 'Phnum Sruoch',
    name_in_khmer: 'ភ្នំស្រួច',
    district_code: 5,
  },
  {
    code: 507,
    name: 'Samraong Tong',
    name_in_khmer: 'សំរោងទង',
    district_code: 5,
  },
  { code: 508, name: 'Thpong', name_in_khmer: 'ថ្ពង', district_code: 5 },
  { code: 601, name: 'Baray', name_in_khmer: 'បារាយណ៍', district_code: 6 },
  {
    code: 602,
    name: 'Kampong Svay',
    name_in_khmer: 'កំពង់ស្វាយ',
    district_code: 6,
  },
  {
    code: 603,
    name: 'Stueng Saen',
    name_in_khmer: 'ស្ទឹងសែន',
    district_code: 6,
  },
  {
    code: 604,
    name: 'Prasat Ballangk',
    name_in_khmer: 'ប្រាសាទបល្ល័ង្គ',
    district_code: 6,
  },
  {
    code: 605,
    name: 'Prasat Sambour',
    name_in_khmer: 'ប្រាសាទសំបូរ',
    district_code: 6,
  },
  { code: 606, name: 'Sandan', name_in_khmer: 'សណ្ដាន់', district_code: 6 },
  { code: 607, name: 'Santuk', name_in_khmer: 'សន្ទុក', district_code: 6 },
  { code: 608, name: 'Stoung', name_in_khmer: 'ស្ទោង', district_code: 6 },
  { code: 609, name: 'Taing Kouk', name_in_khmer: 'តាំងគោក', district_code: 6 },
  {
    code: 701,
    name: 'Angkor Chey',
    name_in_khmer: 'អង្គរជ័យ',
    district_code: 7,
  },
  {
    code: 702,
    name: 'Banteay Meas',
    name_in_khmer: 'បន្ទាយមាស',
    district_code: 7,
  },
  { code: 703, name: 'Chhuk', name_in_khmer: 'ឈូក', district_code: 7 },
  { code: 704, name: 'Chum Kiri', name_in_khmer: 'ជុំគិរី', district_code: 7 },
  { code: 705, name: 'Dang Tong', name_in_khmer: 'ដងទង់', district_code: 7 },
  {
    code: 706,
    name: 'Kampong Trach',
    name_in_khmer: 'កំពង់ត្រាច',
    district_code: 7,
  },
  { code: 707, name: 'Tuek Chhou', name_in_khmer: 'ទឹកឈូ', district_code: 7 },
  { code: 708, name: 'Kampot', name_in_khmer: 'កំពត', district_code: 7 },
  {
    code: 801,
    name: 'Kandal Stueng',
    name_in_khmer: 'កណ្ដាលស្ទឹង',
    district_code: 8,
  },
  { code: 802, name: 'Kien Svay', name_in_khmer: 'កៀនស្វាយ', district_code: 8 },
  {
    code: 803,
    name: 'Khsach Kandal',
    name_in_khmer: 'ខ្សាច់កណ្ដាល',
    district_code: 8,
  },
  { code: 804, name: 'Kaoh Thum', name_in_khmer: 'កោះធំ', district_code: 8 },
  { code: 805, name: 'Leuk Daek', name_in_khmer: 'លើកដែក', district_code: 8 },
  { code: 806, name: 'Lvea Aem', name_in_khmer: 'ល្វាឯម', district_code: 8 },
  {
    code: 807,
    name: 'Mukh Kampul',
    name_in_khmer: 'មុខកំពូល',
    district_code: 8,
  },
  {
    code: 808,
    name: 'Angk Snuol',
    name_in_khmer: 'អង្គស្នួល',
    district_code: 8,
  },
  { code: 809, name: 'Ponhea Lueu', name_in_khmer: 'ពញាឮ', district_code: 8 },
  { code: 810, name: "S'ang", name_in_khmer: 'ស្អាង', district_code: 8 },
  { code: 811, name: 'Ta Khmau', name_in_khmer: 'តាខ្មៅ', district_code: 8 },
  {
    code: 901,
    name: 'Botum Sakor',
    name_in_khmer: 'បុទុមសាគរ',
    district_code: 9,
  },
  {
    code: 902,
    name: 'Kiri Sakor',
    name_in_khmer: 'គិរីសាគរ',
    district_code: 9,
  },
  { code: 903, name: 'Kaoh Kong', name_in_khmer: 'កោះកុង', district_code: 9 },
  {
    code: 904,
    name: 'Khemara Phoumin',
    name_in_khmer: 'ខេមរភូមិន្ទ',
    district_code: 9,
  },
  {
    code: 905,
    name: 'Mondol Seima',
    name_in_khmer: 'មណ្ឌលសីមា',
    district_code: 9,
  },
  {
    code: 906,
    name: 'Srae Ambel',
    name_in_khmer: 'ស្រែ អំបិល',
    district_code: 9,
  },
  { code: 907, name: 'Thma Bang', name_in_khmer: 'ថ្មបាំង', district_code: 9 },
  { code: 1001, name: 'Chhloung', name_in_khmer: 'ឆ្លូង', district_code: 10 },
  { code: 1002, name: 'Kracheh', name_in_khmer: 'ក្រចេះ', district_code: 10 },
  {
    code: 1003,
    name: 'Prek Prasab',
    name_in_khmer: 'ព្រែកប្រសព្វ',
    district_code: 10,
  },
  { code: 1004, name: 'Sambour', name_in_khmer: 'សំបូរ', district_code: 10 },
  { code: 1005, name: 'Snuol', name_in_khmer: 'ស្នួល', district_code: 10 },
  {
    code: 1006,
    name: 'Chetr Borei',
    name_in_khmer: 'ចិត្របុរី',
    district_code: 10,
  },
  {
    code: 1101,
    name: 'Kaev Seima',
    name_in_khmer: 'កែវសីមា',
    district_code: 11,
  },
  {
    code: 1102,
    name: 'Kaoh Nheaek',
    name_in_khmer: 'កោះញែក',
    district_code: 11,
  },
  { code: 1103, name: 'Ou Reang', name_in_khmer: 'អូររាំង', district_code: 11 },
  {
    code: 1104,
    name: 'Pech Chreada',
    name_in_khmer: 'ពេជ្រាដា',
    district_code: 11,
  },
  {
    code: 1105,
    name: 'Saen Monourom',
    name_in_khmer: 'សែនមនោរម្យ',
    district_code: 11,
  },
  {
    code: 1201,
    name: 'Chamkar Mon',
    name_in_khmer: 'ចំការមន',
    district_code: 12,
  },
  { code: 1202, name: 'Doun Penh', name_in_khmer: 'ដូនពេញ', district_code: 12 },
  {
    code: 1203,
    name: 'Prampir Meakkakra',
    name_in_khmer: '៧មករា',
    district_code: 12,
  },
  { code: 1204, name: 'Tuol Kouk', name_in_khmer: 'ទួលគោក', district_code: 12 },
  { code: 1205, name: 'Dangkao', name_in_khmer: 'ដង្កោ', district_code: 12 },
  { code: 1206, name: 'Mean Chey', name_in_khmer: 'មានជ័យ', district_code: 12 },
  {
    code: 1207,
    name: 'Russey Keo',
    name_in_khmer: 'ឫស្សីកែវ',
    district_code: 12,
  },
  { code: 1208, name: 'Saensokh', name_in_khmer: 'សែនសុខ', district_code: 12 },
  {
    code: 1209,
    name: 'Pur SenChey',
    name_in_khmer: 'ពោធិ៍សែនជ័យ',
    district_code: 12,
  },
  {
    code: 1210,
    name: 'Chraoy Chongvar',
    name_in_khmer: 'ជ្រោយចង្វារ',
    district_code: 12,
  },
  {
    code: 1211,
    name: 'Praek Pnov',
    name_in_khmer: 'ព្រែកព្នៅ',
    district_code: 12,
  },
  {
    code: 1212,
    name: 'Chbar Ampov',
    name_in_khmer: 'ច្បារអំពៅ',
    district_code: 12,
  },
  {
    code: 1213,
    name: 'Boeng Keng Kang',
    name_in_khmer: 'បឹងកេងកង',
    district_code: 12,
  },
  { code: 1214, name: 'Kamboul', name_in_khmer: 'កំបូល', district_code: 12 },
  { code: 1301, name: 'Chey Saen', name_in_khmer: 'ជ័យសែន', district_code: 13 },
  { code: 1302, name: 'Chhaeb', name_in_khmer: 'ឆែប', district_code: 13 },
  {
    code: 1303,
    name: 'Choam Ksant',
    name_in_khmer: 'ជាំក្សាន្ដ',
    district_code: 13,
  },
  { code: 1304, name: 'Kuleaen', name_in_khmer: 'គូលែន', district_code: 13 },
  { code: 1305, name: 'Rovieng', name_in_khmer: 'រវៀង', district_code: 13 },
  {
    code: 1306,
    name: 'Sangkum Thmei',
    name_in_khmer: 'សង្គមថ្មី',
    district_code: 13,
  },
  {
    code: 1307,
    name: 'Tbaeng Mean Chey',
    name_in_khmer: 'ត្បែងមានជ័យ',
    district_code: 13,
  },
  {
    code: 1308,
    name: 'Preah Vihear',
    name_in_khmer: 'ព្រះវិហារ',
    district_code: 13,
  },
  { code: 1401, name: 'Ba Phnum', name_in_khmer: 'បាភ្នំ', district_code: 14 },
  {
    code: 1402,
    name: 'Kamchay Mear',
    name_in_khmer: 'កំចាយមារ',
    district_code: 14,
  },
  {
    code: 1403,
    name: 'Kampong Trabaek',
    name_in_khmer: 'កំពង់ត្របែក',
    district_code: 14,
  },
  {
    code: 1404,
    name: 'Kanhchriech',
    name_in_khmer: 'កញ្ជ្រៀច',
    district_code: 14,
  },
  { code: 1405, name: 'Me Sang', name_in_khmer: 'មេសាង', district_code: 14 },
  { code: 1406, name: 'Peam Chor', name_in_khmer: 'ពាមជរ', district_code: 14 },
  { code: 1407, name: 'Peam Ro', name_in_khmer: 'ពាមរក៍', district_code: 14 },
  { code: 1408, name: 'Pea Reang', name_in_khmer: 'ពារាំង', district_code: 14 },
  {
    code: 1409,
    name: 'Preah Sdach',
    name_in_khmer: 'ពោធិ៍រៀង',
    district_code: 14,
  },
  {
    code: 1410,
    name: 'Prey Veng',
    name_in_khmer: 'ព្រៃវែង',
    district_code: 14,
  },
  {
    code: 1411,
    name: 'Pur Rieng',
    name_in_khmer: 'ពោធិ៍រៀង',
    district_code: 14,
  },
  {
    code: 1412,
    name: 'Sithor Kandal',
    name_in_khmer: 'ស៊ីធរកណ្ដាល',
    district_code: 14,
  },
  {
    code: 1413,
    name: 'Svay Antor',
    name_in_khmer: 'ស្វាយអន្ទរ',
    district_code: 14,
  },
  { code: 1501, name: 'Bakan', name_in_khmer: 'បាកាន', district_code: 15 },
  { code: 1502, name: 'Kandieng', name_in_khmer: 'កណ្ដៀង', district_code: 15 },
  { code: 1503, name: 'Krakor', name_in_khmer: 'ក្រគរ', district_code: 15 },
  {
    code: 1504,
    name: 'Phnum Kravanh',
    name_in_khmer: 'ភ្នំក្រវាំញ',
    district_code: 15,
  },
  { code: 1505, name: 'Pursat', name_in_khmer: 'ពោធិ៍សាត់', district_code: 15 },
  {
    code: 1506,
    name: 'Veal Veaeng',
    name_in_khmer: 'វាលវែង',
    district_code: 15,
  },
  {
    code: 1507,
    name: 'Ta Lou Senchey',
    name_in_khmer: 'តាលោសែនជ័យ',
    district_code: 15,
  },
  {
    code: 1601,
    name: 'Andoung Meas',
    name_in_khmer: 'អណ្ដូងមាស',
    district_code: 16,
  },
  { code: 1602, name: 'Ban Lung', name_in_khmer: 'បានលុង', district_code: 16 },
  { code: 1603, name: 'Bar Kaev', name_in_khmer: 'បរកែវ', district_code: 16 },
  { code: 1604, name: 'Koun Mom', name_in_khmer: 'កូនមុំ', district_code: 16 },
  { code: 1605, name: 'Lumphat', name_in_khmer: 'លំផាត់', district_code: 16 },
  { code: 1606, name: 'Ou Chum', name_in_khmer: 'អូរជុំ', district_code: 16 },
  {
    code: 1607,
    name: 'Ou Ya Dav',
    name_in_khmer: 'អូរយ៉ាដាវ',
    district_code: 16,
  },
  { code: 1608, name: 'Ta Veaeng', name_in_khmer: 'តាវែង', district_code: 16 },
  { code: 1609, name: 'Veun Sai', name_in_khmer: 'វើនសៃ', district_code: 16 },
  {
    code: 1701,
    name: 'Angkor Chum',
    name_in_khmer: 'អង្គរជុំ',
    district_code: 17,
  },
  {
    code: 1702,
    name: 'Angkor Thum',
    name_in_khmer: 'អង្គរធំ',
    district_code: 17,
  },
  {
    code: 1703,
    name: 'Banteay Srei',
    name_in_khmer: 'បន្ទាយស្រី',
    district_code: 17,
  },
  {
    code: 1704,
    name: 'Chi Kraeng',
    name_in_khmer: 'ជីក្រែង',
    district_code: 17,
  },
  { code: 1706, name: 'Kralanh', name_in_khmer: 'ក្រឡាញ់', district_code: 17 },
  { code: 1707, name: 'Puok', name_in_khmer: 'ពួក', district_code: 17 },
  {
    code: 1709,
    name: 'Prasat Bakong',
    name_in_khmer: 'ប្រាសាទបាគង',
    district_code: 17,
  },
  { code: 1710, name: 'Siem Reap', name_in_khmer: 'សៀមរាប', district_code: 17 },
  {
    code: 1711,
    name: 'Soutr Nikom',
    name_in_khmer: 'សូទ្រនិគម',
    district_code: 17,
  },
  {
    code: 1712,
    name: 'Srei Snam',
    name_in_khmer: 'ស្រីស្នំ',
    district_code: 17,
  },
  { code: 1713, name: 'Svay Leu', name_in_khmer: 'ស្វាយលើ', district_code: 17 },
  { code: 1714, name: 'Varin', name_in_khmer: 'វ៉ារិន', district_code: 17 },
  {
    code: 1801,
    name: 'Preah Sihanouk',
    name_in_khmer: 'ព្រះសីហនុ',
    district_code: 18,
  },
  { code: 1802, name: 'Prey Nob', name_in_khmer: 'ព្រៃនប់', district_code: 18 },
  {
    code: 1803,
    name: 'Stueng Hav',
    name_in_khmer: 'ស្ទឹងហាវ',
    district_code: 18,
  },
  {
    code: 1804,
    name: 'Kampong Seila',
    name_in_khmer: 'កំពង់សីលា',
    district_code: 18,
  },
  {
    code: 1805,
    name: 'Kaoh Rung',
    name_in_khmer: 'កោះរ៉ុង',
    district_code: 18,
  },
  { code: 1901, name: 'Sesan', name_in_khmer: 'សេសាន', district_code: 19 },
  { code: 1902, name: 'Siem Bouk', name_in_khmer: 'សៀមបូក', district_code: 19 },
  {
    code: 1903,
    name: 'Siem Pang',
    name_in_khmer: 'សៀមប៉ាង',
    district_code: 19,
  },
  {
    code: 1904,
    name: 'Stueng Traeng',
    name_in_khmer: 'ស្ទឹងត្រែង',
    district_code: 19,
  },
  {
    code: 1905,
    name: 'Thala Barivat',
    name_in_khmer: 'ថាឡាបរិវ៉ាត់',
    district_code: 19,
  },
  {
    code: 1906,
    name: 'Borei Ou Svay Senchey',
    name_in_khmer: 'បុរីអូរស្វាយសែនជ័យ',
    district_code: 19,
  },
  { code: 2001, name: 'Chantrea', name_in_khmer: 'ចន្ទ្រា', district_code: 20 },
  {
    code: 2002,
    name: 'Kampong Rou',
    name_in_khmer: 'កំពង់រោទិ៍',
    district_code: 20,
  },
  { code: 2003, name: 'Rumduol', name_in_khmer: 'រំដួល', district_code: 20 },
  {
    code: 2004,
    name: 'Romeas Haek',
    name_in_khmer: 'រមាសហែក',
    district_code: 20,
  },
  {
    code: 2005,
    name: 'Svay Chrum',
    name_in_khmer: 'ស្វាយជ្រំ',
    district_code: 20,
  },
  {
    code: 2006,
    name: 'Svay Rieng',
    name_in_khmer: 'ស្វាយរៀង',
    district_code: 20,
  },
  {
    code: 2007,
    name: 'Svay Teab',
    name_in_khmer: 'ស្វាយទាប',
    district_code: 20,
  },
  { code: 2008, name: 'Bavet', name_in_khmer: 'បាវិត', district_code: 20 },
  {
    code: 2101,
    name: 'Angkor Borei',
    name_in_khmer: 'អង្គរបូរី',
    district_code: 21,
  },
  { code: 2102, name: 'Bati', name_in_khmer: 'បាទី', district_code: 21 },
  {
    code: 2103,
    name: 'Borei Cholsar',
    name_in_khmer: 'បូរីជលសារ',
    district_code: 21,
  },
  {
    code: 2104,
    name: 'Kiri Vong',
    name_in_khmer: 'គីរីវង់',
    district_code: 21,
  },
  {
    code: 2105,
    name: 'Kaoh Andaet',
    name_in_khmer: 'កោះអណ្ដែត',
    district_code: 21,
  },
  {
    code: 2106,
    name: 'Prey Kabbas',
    name_in_khmer: 'ព្រៃកប្បាស',
    district_code: 21,
  },
  { code: 2107, name: 'Samraong', name_in_khmer: 'សំរោង', district_code: 21 },
  { code: 2108, name: 'Doun Kaev', name_in_khmer: 'ដូនកែវ', district_code: 21 },
  {
    code: 2109,
    name: 'Tram Kak',
    name_in_khmer: 'ត្រាំកក់',
    district_code: 21,
  },
  { code: 2110, name: 'Treang', name_in_khmer: 'ទ្រាំង', district_code: 21 },
  {
    code: 2201,
    name: 'Anlong Veaeng',
    name_in_khmer: 'អន្លង់វែង',
    district_code: 22,
  },
  {
    code: 2202,
    name: 'Banteay Ampil',
    name_in_khmer: 'បន្ទាយអំពិល',
    district_code: 22,
  },
  {
    code: 2203,
    name: 'Chong Kal',
    name_in_khmer: 'ចុងកាល់',
    district_code: 22,
  },
  { code: 2204, name: 'Samraong', name_in_khmer: 'សំរោង', district_code: 22 },
  {
    code: 2205,
    name: 'Trapeang Prasat',
    name_in_khmer: 'ត្រពាំងប្រាសាទ',
    district_code: 22,
  },
  {
    code: 2301,
    name: "Damnak Chang'aeur",
    name_in_khmer: 'ដំណាក់ចង្អើរ',
    district_code: 23,
  },
  { code: 2302, name: 'Kaeb', name_in_khmer: 'កែប', district_code: 23 },
  { code: 2401, name: 'Pailin', name_in_khmer: 'ប៉ៃលិន', district_code: 24 },
  {
    code: 2402,
    name: 'Sala Krau',
    name_in_khmer: 'សាលាក្រៅ',
    district_code: 24,
  },
  { code: 2501, name: 'Dambae', name_in_khmer: 'តំបែរ', district_code: 25 },
  {
    code: 2502,
    name: 'Krouch Chhmar',
    name_in_khmer: 'ក្រូចឆ្មារ',
    district_code: 25,
  },
  { code: 2503, name: 'Memot', name_in_khmer: 'មេមត់', district_code: 25 },
  {
    code: 2504,
    name: 'Ou Reang Ov',
    name_in_khmer: 'អូររាំងឪ',
    district_code: 25,
  },
  {
    code: 2505,
    name: 'Ponhea Kraek',
    name_in_khmer: 'ពញាក្រែក',
    district_code: 25,
  },
  { code: 2506, name: 'Suong', name_in_khmer: 'សួង', district_code: 25 },
  {
    code: 2507,
    name: 'Tboung Khmum',
    name_in_khmer: 'ត្បូងឃ្មុំ',
    district_code: 25,
  },
];
