export const provinces = [
  {
    country_code: 'KH',
    code: 1,
    name: 'Banteay Meanchey',
    name_in_khmer: 'បន្ទាយមានជ័យ',
  },
  {
    country_code: 'KH',
    code: 2,
    name: 'Battambang',
    name_in_khmer: 'បាត់ដំបង',
  },
  {
    country_code: 'KH',
    code: 3,
    name: 'Kampong Cham',
    name_in_khmer: 'កំពង់ចាម',
  },
  {
    country_code: 'KH',
    code: 4,
    name: 'Kampong Chhnang',
    name_in_khmer: 'កំពង់ឆ្នាំង',
  },
  {
    country_code: 'KH',
    code: 5,
    name: 'Kampong Speu',
    name_in_khmer: 'កំពង់ស្ពឺ',
  },
  {
    country_code: 'KH',
    code: 6,
    name: 'Kampong Thom',
    name_in_khmer: 'កំពង់ធំ',
  },
  { country_code: 'KH', code: 7, name: 'Kampot', name_in_khmer: 'កំពត' },
  { country_code: 'KH', code: 8, name: 'Kandal', name_in_khmer: 'កណ្តាល' },
  { country_code: 'KH', code: 9, name: 'Koh Kong', name_in_khmer: 'កោះកុង' },
  { country_code: 'KH', code: 10, name: 'Kratié', name_in_khmer: 'ក្រចេះ' },
  {
    country_code: 'KH',
    code: 11,
    name: 'Mondulkiri',
    name_in_khmer: 'មណ្ឌលគិរី',
  },
  {
    country_code: 'KH',
    code: 12,
    name: 'Phnom Penh',
    name_in_khmer: 'ភ្នំពេញ',
  },
  {
    country_code: 'KH',
    code: 13,
    name: 'Preah Vihear',
    name_in_khmer: 'ព្រះវិហារ',
  },
  { country_code: 'KH', code: 14, name: 'Prey Veng', name_in_khmer: 'ព្រៃវែង' },
  { country_code: 'KH', code: 15, name: 'Pursat', name_in_khmer: 'ពោធិ៍សាត់' },
  {
    country_code: 'KH',
    code: 16,
    name: 'Ratanak Kiri',
    name_in_khmer: 'រតនគិរី',
  },
  { country_code: 'KH', code: 17, name: 'Siem Reap', name_in_khmer: 'សៀមរាប' },
  {
    country_code: 'KH',
    code: 18,
    name: 'Preah Sihanouk',
    name_in_khmer: 'ព្រះសីហនុ',
  },
  {
    country_code: 'KH',
    code: 19,
    name: 'Stung Treng',
    name_in_khmer: 'ស្ទឹងត្រែង',
  },
  {
    country_code: 'KH',
    code: 20,
    name: 'Svay Rieng',
    name_in_khmer: 'ស្វាយរៀង',
  },
  { country_code: 'KH', code: 21, name: 'Takéo', name_in_khmer: 'តាកែវ' },
  {
    country_code: 'KH',
    code: 22,
    name: 'Oddar Meanchey',
    name_in_khmer: 'ឧត្តរមានជ័យ',
  },
  { country_code: 'KH', code: 23, name: 'Kep', name_in_khmer: 'កែប' },
  { country_code: 'KH', code: 24, name: 'Pailin', name_in_khmer: 'ប៉ៃលិន' },
  {
    country_code: 'KH',
    code: 25,
    name: 'Tboung Khmum',
    name_in_khmer: 'ត្បូងឃ្មុំ',
  },
];
